---
- name: Load common variables
  include_vars:
    file: "../config/defaults/main.yml"

- name: Ensure Open5GS namespace exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ core_ns }}"
    state: present

# ------------------------
# Step 1: Clean existing cert-pvc
# ------------------------
- name: Delete existing cert-pvc if exists
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: PersistentVolumeClaim
    name: cert-pvc
    namespace: "{{ core_ns }}"
  ignore_errors: yes

- name: Delete PV linked to cert-pvc if exists
  shell: |
    PV=$(kubectl get pv --no-headers | grep cert-pvc | awk '{print $1}')
    if [[ ! -z "$PV" ]]; then
      kubectl delete pv $PV
    fi
  args:
    executable: /bin/bash
  ignore_errors: yes

# ------------------------
# Step 2: Deploy Free5GC via Helm
# ------------------------
- name: Deploy free5gc using Helm
  when: rru == 'rfsim'
  kubernetes.core.helm:
    name: free5gc
    chart_ref: "{{ [repo_dest, 'charts', 'free5gc'] | path_join }}"
    release_namespace: "{{ core_ns }}"
    state: present
    wait: true
    atomic: true
    timeout: 1200s
    values:
      nodeSelector:
        kubernetes.io/hostname: "{{ core_node_name }}"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - "{{ core_node_name }}"
      upf:
        privileged: true
        capabilities:
          add:
            - NET_ADMIN
            - SYS_MODULE
