---
- name: Load common variables
  include_vars:
    file: "../config/defaults/main.yml"

- name: Ensure Free5GC namespace exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ core_ns }}"
    state: present

- name: Delete cert-pvc if it exists
  kubernetes.core.k8s:
    state: absent
    kind: PersistentVolumeClaim
    name: cert-pvc
    namespace: "{{ core_ns }}"
  ignore_errors: true

- name: Deploy Free5GC using Helm
  when: rru == 'rfsim'
  kubernetes.core.helm:
    name: free5gc
    chart_ref: "{{ [repo_dest, 'charts', 'free5gc'] | path_join }}"
    release_namespace: "{{ core_ns }}"
    state: present
    wait: true
    atomic: true
    timeout: 1200s
    values:
      # Scheduler → tous les pods sur le core node
      nodeSelector:
        kubernetes.io/hostname: "{{ core_node_name }}"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - "{{ core_node_name }}"
      # UPF privileges pour gtp5g
      upf:
        privileged: true
        capabilities:
          add:
            - NET_ADMIN
            - SYS_MODULE
