---
- name: Load common variables
  include_vars:
    file: "../../common/defaults/main.yml"

- name: Check if yq is already installed
  ansible.builtin.stat:
    path: "{{ yq_bin_path }}"
  register: yq_bin

- name: Download yq binary
  ansible.builtin.shell: |
    set -e
    if command -v curl >/dev/null 2>&1; then
      curl -L --fail "{{ yq_url }}" -o "{{ yq_bin_path }}"
    elif command -v wget >/dev/null 2>&1; then
      wget -O "{{ yq_bin_path }}" "{{ yq_url }}"
    else
      echo "Neither curl nor wget found" >&2
      exit 1
    fi
  args:
    creates: "{{ yq_bin_path }}"
  when: not yq_bin.stat.exists
  become: true

- name: Ensure yq is executable
  ansible.builtin.file:
    path: "{{ yq_bin_path }}"
    mode: '0755'
    state: file
  become: true

- name: Load active 5G profile
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/../group_vars/all/5g_profile_{{ fiveg_profile | default('default') }}.yaml"
    name: fiveg

- name: Validate PLMN
  assert:
    that:
      - fiveg.plmn.mcc is defined
      - fiveg.plmn.mnc is defined
      - fiveg.plmn.tac is defined

- name: Configure srsRAN for free5gc
  ansible.builtin.include_tasks: config_free5gc.yml
  when: core == 'free5gc'

- name: Configure srsRAN for open5gs
  ansible.builtin.include_tasks: config_open5gs.yml
  when: core == 'open5gs'
