---

- name: Deploy srsRAN gNB
  include_tasks: deploy_gnb.yml

- name: Deploy Telegraf
  include_tasks: deploy_telegraf.yml

- name: Deploy srsRAN UEs
  include_tasks: deploy_srsues.yml
  when: rru == 'rfsim'
