---
ping_duration: 30
iperf_duration: 35 # We start iperf slightly before ping and want to make sure it runs throughout
sleep: 10

# Use helpers/scenario_builder.py to build scenario lists
scenarios:
  - {ping_rate: 1, ping_size: 64, iperf_protocol: "None", iperf_rate: "None", iperf_dir: "None", bg_traffic: "None", ping_args: "-i 1 -s 56", iperf_args: ""}
  - {ping_rate: 0.1, ping_size: 64, iperf_protocol: "None", iperf_rate: "None", iperf_dir: "None", bg_traffic: "None", ping_args: "-i 0.1 -s 56", iperf_args: ""}
  - {iperf_protocol: "tcp", iperf_rate: "10M", iperf_dir: "up", ping_rate: 1, ping_size: 64, bg_traffic: "TCP_10M_up", ping_args: "-i 1 -s 56", iperf_args: "-b 10M"}
  - {iperf_protocol: "tcp", iperf_rate: "10M", iperf_dir: "up", ping_rate: 0.1, ping_size: 64, bg_traffic: "TCP_10M_up", ping_args: "-i 0.1 -s 56", iperf_args: "-b 10M"}
  - {iperf_protocol: "tcp", iperf_rate: "10M", iperf_dir: "down", ping_rate: 1, ping_size: 64, bg_traffic: "TCP_10M_down", ping_args: "-i 1 -s 56", iperf_args: "-b 10M -R"}
  - {iperf_protocol: "tcp", iperf_rate: "10M", iperf_dir: "down", ping_rate: 0.1, ping_size: 64, bg_traffic: "TCP_10M_down", ping_args: "-i 0.1 -s 56", iperf_args: "-b 10M -R"}
  - {iperf_protocol: "udp", iperf_rate: "10M", iperf_dir: "up", ping_rate: 1, ping_size: 64, bg_traffic: "UDP_10M_up", ping_args: "-i 1 -s 56", iperf_args: "-u -b 10M"}
  - {iperf_protocol: "udp", iperf_rate: "10M", iperf_dir: "up", ping_rate: 0.1, ping_size: 64, bg_traffic: "UDP_10M_up", ping_args: "-i 0.1 -s 56", iperf_args: "-u -b 10M"}
  - {iperf_protocol: "udp", iperf_rate: "10M", iperf_dir: "down", ping_rate: 1, ping_size: 64, bg_traffic: "UDP_10M_down", ping_args: "-i 1 -s 56", iperf_args: "-u -b 10M -R"}
  - {iperf_protocol: "udp", iperf_rate: "10M", iperf_dir: "down", ping_rate: 0.1, ping_size: 64, bg_traffic: "UDP_10M_down", ping_args: "-i 0.1 -s 56", iperf_args: "-u -b 10M -R"}
