- name: Debug parameters
  debug:
    msg: |
      UE: {{ current_ue }}
      Bind IP: {{ ue_ip }}
      Server IP: {{ target_server }}
      Duration: {{ ping_duration }}s

- name: Execute all scenarios
  include_tasks: scenario.yml
  loop: "{{ scenarios }}"
  loop_control:
    loop_var: s
